"""Render generated Godot branch-traversal tests from quest packages."""

from __future__ import annotations

import json
from pathlib import Path

from .manifest import QuestPackage, package_content_dirs, package_content_paths

ROOT = Path(__file__).resolve().parents[2]
GENERATED_ROOT = ROOT / "tests" / "godot" / "generated"


def test_output_path(package: QuestPackage) -> Path:
    package_id = str(package.manifest["id"])
    slug = package_id.removeprefix("package.")
    return GENERATED_ROOT / f"test_quest_package_{slug}.gd"


def _godot_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _godot_string_name(value: str) -> str:
    return f"&{_godot_string(value)}"


def _render_content_dirs(package: QuestPackage) -> str:
    dirs: list[str] = []
    for directory in package_content_dirs(package):
        relative_parent = directory.relative_to(ROOT).as_posix()
        dirs.append(_godot_string("res://" + relative_parent))
    return ", ".join(dirs)


def _render_branch_dictionary(branch: dict[str, object]) -> str:
    transitions = ", ".join(_godot_string_name(str(item)) for item in branch.get("transitions", []))
    expect = branch.get("expect", {})
    expect_state = _godot_string_name(str(expect.get("quest_state", "")))
    flag_entries: list[str] = []
    for key, value in sorted((expect.get("flags") or {}).items()):
        flag_entries.append(
            f'\t\t{{"flag": {_godot_string_name(str(key))}, "value": {str(value).lower()}}}'
        )
    expect_flags = "[\n" + ",\n".join(flag_entries) + "\n\t]" if flag_entries else "[]"
    setup_entries: list[str] = []
    for key, value in sorted((branch.get("setup") or {}).items()):
        setup_entries.append(f"\t\t{_godot_string_name(str(key))}: {str(value).lower()},")
    setup_block = "{\n" + "\n".join(setup_entries) + "\n\t}" if setup_entries else "{}"
    require_entries: list[str] = []
    for key, value in sorted((branch.get("require_flags") or {}).items()):
        require_entries.append(f"\t\t{_godot_string_name(str(key))}: {str(value).lower()},")
    require_block = "{\n" + "\n".join(require_entries) + "\n\t}" if require_entries else "{}"
    return (
        "\t{\n"
        f'\t\t"id": {_godot_string_name(str(branch["id"]))},\n'
        f"\t\t\"transitions\": [{transitions}],\n"
        f"\t\t\"setup\": {setup_block},\n"
        f"\t\t\"require_flags\": {require_block},\n"
        f"\t\t\"expect_state\": {expect_state},\n"
        f"\t\t\"expect_flags\": {expect_flags},\n"
        "\t}"
    )


def render_godot_test(package: QuestPackage) -> str:
    manifest = package.manifest
    package_id = str(manifest["id"])
    quest_record_path = package.root / str(manifest["quest"])
    quest_id = json.loads(quest_record_path.read_text(encoding="utf-8"))["id"]
    landmark_beats = manifest.get("bindings", {}).get("landmark_beats", [])
    beat_lines = ",\n".join(f"\t{_godot_string_name(str(beat))}" for beat in landmark_beats)
    content_dirs = _render_content_dirs(package)
    branch_blocks = ",\n".join(_render_branch_dictionary(branch) for branch in package.branch_map.get("branches", []))
    relative_package = package.root.relative_to(ROOT).as_posix()
    return "\n".join(
        [
            "# Generated by tools/generate_quest_package_tests.py",
            f"# Source package: {relative_package}/package.json",
            "# Do not edit by hand.",
            'extends "res://tests/godot/test_case.gd"',
            "",
            f"const PACKAGE_ID := {_godot_string_name(package_id)}",
            f"const QUEST_ID := {_godot_string_name(str(quest_id))}",
            "const LANDMARK_BEATS: Array[StringName] = [",
            beat_lines,
            "]",
            f"const CONTENT_DIRS: Array[String] = [{content_dirs}]",
            "const BRANCHES: Array[Dictionary] = [",
            branch_blocks,
            "]",
            "",
            "var db: ContentDB",
            "var state: GameState",
            "var evaluator: StateRuleEvaluator",
            "var manager: QuestManager",
            "",
            "func before_each() -> void:",
            "\tdb = ContentDB.new()",
            '\tassert_true(db.load_from_directories(CONTENT_DIRS), "quest package corpus should load")',
            "\tstate = GameState.new()",
            "\tevaluator = StateRuleEvaluator.new()",
            "\tmanager = QuestManager.new(db, state, evaluator)",
            "",
            "func test_landmark_beat_bindings_are_declared() -> void:",
            '\tassert_false(LANDMARK_BEATS.is_empty(), "package must declare at least one landmark beat")',
            "\tfor beat in LANDMARK_BEATS:",
            '\t\tassert_true(String(beat).begins_with("beat.landmark."), "landmark beat ids must use beat.landmark.* prefix")',
            "",
            "func test_generated_branch_traversal_paths() -> void:",
            "\tfor branch in BRANCHES:",
            "\t\tvar branch_state := GameState.new()",
            "\t\tvar branch_manager := QuestManager.new(db, branch_state, StateRuleEvaluator.new())",
            '\t\tassert_true(branch_manager.start_quest(QUEST_ID), "start should succeed for %s" % branch["id"])',
            "\t\tfor flag_name in branch.get(\"setup\", {}):",
            "\t\t\tbranch_state.set_flag(flag_name, branch[\"setup\"][flag_name])",
            "\t\tfor require_flag in branch.get(\"require_flags\", {}):",
            "\t\t\tbranch_state.set_flag(require_flag, branch[\"require_flags\"][require_flag])",
            "\t\tfor transition_id in branch.get(\"transitions\", []):",
            '\t\t\tassert_true(branch_manager.transition(QUEST_ID, transition_id), "transition should succeed: %s" % transition_id)',
            '\t\tassert_eq(branch_state.get_quest_state(QUEST_ID), branch["expect_state"])',
            "\t\tfor expected_flag in branch.get(\"expect_flags\", []):",
            '\t\t\tassert_eq(branch_state.get_flag(expected_flag["flag"]), expected_flag["value"])',
            "",
        ]
    ) + "\n"
