extends "res://tests/godot/test_case.gd"

func before_each() -> void:
	DoorNavigator.load_manifest(true)

func test_transition_manifest_exposes_release_scene_ids() -> void:
	var active_scene_ids := DoorNavigator.get_active_scene_ids()

	assert_array_contains(active_scene_ids, &"forge", "Forge should stay registered as an active transition scene")
	assert_array_contains(active_scene_ids, &"reval_east", "Lower Town slice should stay registered as a playable transition scene")
	assert_eq(DoorNavigator.has_active_scene(&"archive_only"), false, "Unknown scenes must not be active")

func test_transition_manifest_includes_dev_traversal_scenes() -> void:
	assert_true(DoorNavigator.has_active_scene(&"reval_center"), "Market civic quarter should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"reval_north"), "North quarter should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"reval_monastery"), "Monastery district should be traversable in dev")
	assert_false(DoorNavigator.has_active_scene(&"market_civic_quarter"), "Market square is unified into reval_center")
	assert_true(DoorNavigator.has_active_scene(&"st_olafs_guild_hall"), "Guild hall should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"town_hall"), "Town Hall interior should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"viru_gate_foreland"), "Viru Gate foreland should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"reval_harbor_north"), "Coastal Gate landing should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"reval_harbor_east"), "Kalamaja fishing shore should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"reval_archbishops_garden"), "Archbishop's Garden should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"reval_toompea"), "Toompea quarter should be traversable in dev")
	assert_true(DoorNavigator.has_active_scene(&"reval_south"), "South quarter should be traversable in dev")
	assert_false(DoorNavigator.has_active_scene(&"harbor_warehouse"), "Harbor warehouse must be retired from dev traversal")

func test_transition_manifest_resolves_paths_and_spawns() -> void:
	assert_eq(DoorNavigator.get_scene_path(&"forge"), "res://scenes/reval_east/forge/forge.tscn")
	assert_true(DoorNavigator.has_spawn(&"forge", &"door_courtyard"), "Forge must expose its stable courtyard spawn")
	assert_true(DoorNavigator.has_spawn(&"forge", &"smithy_start"), "Forge must expose its new-game start spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_east", &"street_start"), "Lower Town must expose its Start spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_east", &"forge"), "Lower Town must expose its smithy spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_east", &"vana_turg_boundary"), "Lower Town must expose its west boundary spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_center", &"from_reval_east"), "Center must expose its east-entry spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_center", &"to_reval_toompea"), "Center must expose its west-entry spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_center", &"to_reval_south"), "Center must expose its south-entry spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_center", &"to_town_hall"), "Center must expose its Town Hall threshold spawn")
	assert_true(DoorNavigator.has_spawn(&"town_hall", &"from_reval_center"), "Town Hall must expose its square-entry spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_monastery", &"from_reval_center"), "Monastery district must expose its civic-entry spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_monastery", &"from_reval_north"), "Monastery district must expose its merchant-entry spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_north", &"from_monastery"), "Merchant district must expose its monastery-entry spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_east", &"from_reval_south"), "East must expose its internal south-quarter spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_toompea", &"from_reval_north"), "Toompea must expose its Pikk Jalg spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_toompea", &"from_archbishops_garden"), "Toompea must expose its garden spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_archbishops_garden", &"from_reval_toompea"))
	assert_true(DoorNavigator.has_spawn(&"reval_archbishops_garden", &"from_reval_center"))
	assert_true(DoorNavigator.has_spawn(&"reval_archbishops_garden", &"from_reval_south"))
	assert_true(DoorNavigator.has_spawn(&"reval_south", &"from_reval_east"), "South must expose its internal Viru-quarter spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_south", &"from_archbishops_garden"), "South must expose its garden descent spawn")
	assert_true(DoorNavigator.has_spawn(&"viru_gate_foreland", &"from_reval_east"), "Viru foreland must expose its Workers' District spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_harbor_north", &"from_reval_north"), "Coastal Gate landing must expose its Pikk Street spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_harbor_north", &"from_harbor_east"), "Coastal Gate landing must expose its Kalamaja spawn")
	assert_false(DoorNavigator.has_spawn(&"reval_harbor_east", &"from_reval_east"), "Kalamaja must not expose a topologically false Viru road spawn")
	assert_true(DoorNavigator.has_spawn(&"reval_harbor_east", &"from_harbor_north"), "Kalamaja must expose its Coastal Gate landing spawn")
	assert_false(DoorNavigator.has_spawn(&"reval_south", &"from_karja_gate"), "Karja Gate must not remain a district-transition spawn")
	assert_false(DoorNavigator.has_spawn(&"reval_center", &"to_market"), "Retired market self-transition spawn must stay absent")
	assert_false(DoorNavigator.has_spawn(&"forge", &"main"), "Legacy forge spawn alias must be retired")
	assert_false(DoorNavigator.has_spawn(&"reval_east", &"south_1"), "Legacy district-edge spawns must be retired")
	assert_false(DoorNavigator.has_spawn(&"forge", &"missing_spawn"), "Missing spawn IDs must not resolve")
