extends Control

## Credits screen. Reads the committed CREDITS.md (the single source of truth
## generated by tools/generate_credits.py) and renders it with light Markdown
## to BBCode conversion so attribution stays in sync with the audio manifests.

const CREDITS_PATH := "res://CREDITS.md"
const MAIN_MENU := "res://scenes/menu/main_menu.tscn"

@onready var _body: RichTextLabel = $Scroll/Body
@onready var _back: RichTextLabel = $BackLabel


func _ready() -> void:
	_body.bbcode_enabled = true
	_body.text = _markdown_to_bbcode(_load_credits())
	_back.mouse_default_cursor_shape = Control.CURSOR_POINTING_HAND
	_back.gui_input.connect(_on_back_input)
	_back.grab_focus()


func _load_credits() -> String:
	# CREDITS.md is shipped as a plain file (see export_presets.cfg include_filter).
	if not FileAccess.file_exists(CREDITS_PATH):
		return "Credits file not found."
	return FileAccess.get_file_as_string(CREDITS_PATH)


func _markdown_to_bbcode(md: String) -> String:
	var out: PackedStringArray = []
	for raw in md.split("\n"):
		var line := raw
		if line.begins_with("## "):
			line = "[b][font_size=30]%s[/font_size][/b]" % line.substr(3)
		elif line.begins_with("# "):
			line = "[b][font_size=40]%s[/font_size][/b]" % line.substr(2)
		# Emphasis: *scientific name* -> italic. Simple paired-asterisk pass.
		line = _wrap_pairs(line, "*", "[i]", "[/i]")
		out.append(line)
	return "\n".join(out)


func _wrap_pairs(line: String, marker: String, open_tag: String, close_tag: String) -> String:
	var parts := line.split(marker)
	# Odd number of parts => balanced pairs; wrap every second segment.
	if parts.size() % 2 == 0:
		return line  # unbalanced, leave untouched
	var result := ""
	for i in parts.size():
		if i % 2 == 1:
			result += open_tag + parts[i] + close_tag
		else:
			result += parts[i]
	return result


func _on_back_input(event: InputEvent) -> void:
	if _is_activate(event):
		_go_back()


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed(&"ui_cancel"):
		_go_back()


func _go_back() -> void:
	get_tree().change_scene_to_file(MAIN_MENU)


func _is_activate(event: InputEvent) -> bool:
	return (
		event.is_action_pressed(&"ui_accept")
		or (
			event is InputEventMouseButton
			and (event as InputEventMouseButton).button_index == MOUSE_BUTTON_LEFT
			and (event as InputEventMouseButton).pressed
		)
	)
