#!/usr/bin/env python3
"""Keep every Markdown file reachable from the root README.

Index pages listed in INDEXES carry a generated block between DOCS_INDEX_START and
DOCS_INDEX_END. The block links every Markdown file under the index's scope that
the hand-written part of the page does not already link. A nested index replaces
its own subtree, so each file is listed once, by its nearest index.

  python3 tools/docs_index.py           # rewrite generated blocks
  python3 tools/docs_index.py --check   # fail on stale blocks or unreachable docs

Reachability walks relative Markdown links from README.md. A link to a directory
reaches that directory's README.md.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote, unquote

ROOT = Path(__file__).resolve().parent.parent
ENTRY = "README.md"
DOCS_INDEX_START = "<!-- docs-index:start (generated by tools/docs_index.py; do not edit) -->"
DOCS_INDEX_END = "<!-- docs-index:end -->"

# (index page, scope directory). Scopes are recursive.
INDEXES: list[tuple[str, str]] = [
    ("docs/README.md", "docs"),
    ("docs/SYSTEMS/README.md", "docs/SYSTEMS"),
    ("docs/adr/README.md", "docs/adr"),
    ("docs/reports/README.md", "docs/reports"),
    ("docs/tasks/README.md", "docs/tasks"),
    ("docs/SCENES/README.md", "docs/SCENES"),
    ("docs/quests/README.md", "docs/quests"),
    ("docs/lore/README.md", "docs/lore"),
    ("docs/CHARACTERS/README.md", "docs/CHARACTERS"),
    ("docs/CITIZENS/README.md", "docs/CITIZENS"),
    ("docs/CITIZENS/people/README.md", "docs/CITIZENS/people"),
    ("docs/CITIZENS/ledger/README.md", "docs/CITIZENS/ledger"),
    ("docs/CITIZENS/factions/README.md", "docs/CITIZENS/factions"),
    ("characters/README.md", "characters"),
    ("character/README.md", "character"),
    ("scenes/README.md", "scenes"),
    ("history/RESEARCH_INDEX.md", "history"),
    ("story/README.md", "story"),
    ("wiki/README.md", "wiki"),
    ("agents/README.md", "agents"),
    ("content/README.md", "content"),
    ("assets/README.md", "assets"),
    ("generated/README.md", "generated"),
    ("cinematics/README.md", "cinematics"),
]

EXCLUDED_PREFIXES = (".worktrees/", ".godot/", "build/", "bin/", "node_modules/")
LINK_RE = re.compile(r"\]\(\s*<?([^)>\s]+)>?(?:\s+\"[^\"]*\")?\s*\)")
HEADING_RE = re.compile(r"^(#{1,3})\s+(.+?)\s*#*\s*$")


def markdown_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z", "--", "*.md"],
        cwd=ROOT,
        capture_output=True,
        check=True,
    ).stdout.decode("utf-8")
    files = {p for p in out.split("\0") if p}
    return sorted(
        p for p in files if not p.startswith(EXCLUDED_PREFIXES) and (ROOT / p).is_file()
    )


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8", errors="replace")


def strip_block(text: str) -> str:
    start = text.find(DOCS_INDEX_START)
    end = text.find(DOCS_INDEX_END)
    if start == -1 or end == -1 or end < start:
        return text
    return text[:start] + text[end + len(DOCS_INDEX_END):]


def resolve_links(source: str, text: str) -> set[str]:
    targets: set[str] = set()
    base = os.path.dirname(source)
    for raw in LINK_RE.findall(text):
        if re.match(r"^[a-z][a-z0-9+.-]*:", raw) or raw.startswith("#"):
            continue
        rel = unquote(raw.split("#", 1)[0].split("?", 1)[0])
        if not rel:
            continue
        target = os.path.normpath(os.path.join(base, rel)) if not rel.startswith("/") else rel.lstrip("/")
        if (ROOT / target).is_dir():
            readme = os.path.join(target, "README.md")
            if (ROOT / readme).is_file():
                targets.add(os.path.normpath(readme))
            continue
        targets.add(target)
    return targets


def title_of(path: str) -> str:
    """First H1, else the shallowest early heading, else the file name in title case."""
    best: tuple[int, str] | None = None
    for line in read(path).splitlines()[:60]:
        match = HEADING_RE.match(line)
        if not match:
            continue
        title = re.sub(r"[`*_]", "", match.group(2)).strip()
        level = len(match.group(1))
        if title and (best is None or level < best[0]):
            best = (level, title)
        if level == 1:
            break
    if best is None:
        return Path(path).stem.replace("_", " ").replace("-", " ").title()
    return best[1].replace("[", "(").replace("]", ")")


def in_scope(path: str, scope: str) -> bool:
    return path.startswith(scope.rstrip("/") + "/")


def nearest_index(path: str) -> str | None:
    """Return the index page whose scope most tightly contains `path`."""
    best: tuple[int, str] | None = None
    for index, scope in INDEXES:
        if path == index:
            continue
        if in_scope(path, scope):
            depth = scope.count("/") + 1
            if best is None or depth > best[0]:
                best = (depth, index)
    return best[1] if best else None


def render_block(index: str, scope: str, files: list[str]) -> str:
    manual = resolve_links(index, strip_block(read(index)))
    index_dir = os.path.dirname(index)
    entries: list[str] = []
    for path in files:
        if path == index or not in_scope(path, scope):
            continue
        owner = nearest_index(path)
        if owner == index:
            entries.append(path)
        elif owner is not None and owner != index and nearest_index(owner) == index:
            entries.append(owner)
    entries = sorted(set(e for e in entries if e not in manual and e != index))

    groups: dict[str, list[str]] = {}
    for path in entries:
        rel = os.path.relpath(path, scope)
        group = rel.split("/", 1)[0] + "/" if "/" in rel else ""
        groups.setdefault(group, []).append(path)

    lines = [DOCS_INDEX_START, ""]
    if not entries:
        lines.append("_Every file in this folder is linked above._")
    for group in sorted(groups, key=lambda g: (g != "", g.lower())):
        if group:
            lines += [f"#### `{group}`", ""]
        for path in groups[group]:
            href = quote(os.path.relpath(path, index_dir), safe="/._-~")
            lines.append(f"- [{title_of(path)}]({href})")
        lines.append("")
    lines.append(DOCS_INDEX_END)
    return "\n".join(lines)


def apply_block(index: str, block: str) -> str:
    text = read(index) if (ROOT / index).is_file() else ""
    start = text.find(DOCS_INDEX_START)
    end = text.find(DOCS_INDEX_END)
    if start != -1 and end != -1 and end > start:
        return text[:start] + block + text[end + len(DOCS_INDEX_END):]
    heading = "\n## All files in this folder\n\n"
    return text.rstrip("\n") + "\n" + heading + block + "\n"


def reachable(files: list[str]) -> set[str]:
    known = set(files)
    seen: set[str] = set()
    stack = [ENTRY]
    while stack:
        path = stack.pop()
        if path in seen or not (ROOT / path).is_file():
            continue
        seen.add(path)
        if path.endswith(".md"):
            stack.extend(t for t in resolve_links(path, read(path)) if t in known and t not in seen)
    return seen


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    args = parser.parse_args()

    missing = [index for index, _ in INDEXES if not (ROOT / index).is_file()]
    if missing:
        print("Missing index pages (create them with a title first):", *missing, sep="\n  ")
        return 1

    files = markdown_files()
    stale: list[str] = []
    for index, scope in INDEXES:
        updated = apply_block(index, render_block(index, scope, files))
        if updated != read(index):
            stale.append(index)
            if not args.check:
                (ROOT / index).write_text(updated, encoding="utf-8")

    if args.check and stale:
        print("Stale generated index blocks (run python3 tools/docs_index.py):", *stale, sep="\n  ")
        return 1

    orphans = sorted(set(files) - reachable(files))
    if orphans:
        print(f"{len(orphans)} Markdown files are not reachable from {ENTRY}:", *orphans, sep="\n  ")
        print("Link each from its nearest index page, or add an index to INDEXES in tools/docs_index.py.")
        return 1
    if not args.check:
        print(f"Updated {len(stale)} index page(s); all {len(files)} Markdown files reachable from {ENTRY}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
