#!/usr/bin/env python3
"""Generate the active Markdown documentation consistency report.

P0-031 intentionally scans only active documentation. Legacy, archived, and
reference Markdown can contain contradictory old design ideas, so this command
uses a conservative active-doc allowlist plus legacy-status exclusions instead
of walking every .md file in the repository.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

# Re-export the report API from this historical entry point so existing imports
# continue to work after the implementation was split by responsibility.
from active_docs_report_checks import (  # noqa: E402,F401
    check_contradictory_dates,
    check_duplicate_character_names,
    check_missing_references,
    extract_date_values,
    normalize_character_name,
    normalize_event_label,
)
from active_docs_report_common import (  # noqa: E402,F401
    ACTIVE_DOC_DIRS,
    ACTIVE_ROOT_DOCS,
    EXCLUDED_ACTIVE_SUBDIRS,
    LEGACY_STATUSES,
    Issue,
    LinkRecord,
    ReportResult,
    collect_active_docs,
    is_under,
    iter_markdown_files,
    legacy_status,
    read_text,
    rel,
    strip_code_spans,
)
from active_docs_report_fixtures import run_fixture, write_fixture  # noqa: E402,F401
from active_docs_report_links import (  # noqa: E402,F401
    anchors_for,
    check_links,
    is_external_destination,
    iter_link_destinations,
    resolve_link,
    slugify_heading,
    split_local_destination,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "reports" / "active_markdown_report.md"


def render_report(result: ReportResult) -> str:
    issue_counts = Counter(issue.code for issue in result.issues)
    active_links = [link for link in result.links if link.target_is_active is True]
    legacy_or_reference_links = [link for link in result.links if link.target_is_active is False]
    external_links = [link for link in result.links if link.target_path is None]

    lines: list[str] = []
    lines.append("# Active Markdown Documentation Report")
    lines.append("")
    lines.append("Generated by `python3 tools/generate_active_docs_report.py` for TODO P0-031.")
    lines.append("")
    lines.append("## Scope")
    lines.append("")
    lines.append("Active Markdown scanned:")
    lines.append("")
    lines.append("- Root product/task docs: `README.md`, `AGENTS.md`, `TODO.md`.")
    lines.append("- `docs/**/*.md`, excluding generated `docs/reports/**`.")
    lines.append("- Files with explicit legacy status `archive`, `reference`, or `superseded` are excluded even if they match the path rules.")
    lines.append("")
    lines.append("This deliberately excludes legacy root design docs, `characters/`, `scenes/`, `story/`, `history/`, and asset-reference Markdown unless those docs are reconciled into `docs/` or root active docs.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Active Markdown files scanned: `{len(result.active_docs)}`")
    lines.append(f"- Markdown files excluded as archive/reference/out of active scope: `{len(result.excluded_docs)}`")
    lines.append(f"- Local/external links inspected: `{len(result.links)}`")
    lines.append(f"- Links to active Markdown docs: `{len(active_links)}`")
    lines.append(f"- Links to existing archive/reference/non-active local docs: `{len(legacy_or_reference_links)}`")
    lines.append(f"- External links skipped for reachability: `{len(external_links)}`")
    lines.append(f"- Issues found: `{len(result.issues)}`")
    lines.append("")
    lines.append("## Issue counts")
    lines.append("")
    lines.append("| Code | Count |")
    lines.append("| --- | ---: |")
    for code in ("BROKEN_LINK", "BROKEN_ANCHOR", "DUPLICATE_CHARACTER_NAME", "CONTRADICTORY_DATE", "MISSING_REFERENCE"):
        lines.append(f"| `{code}` | {issue_counts[code]} |")
    lines.append("")
    lines.append("## Issues")
    lines.append("")
    if result.issues:
        lines.append("| Code | Location | Detail |")
        lines.append("| --- | --- | --- |")
        for issue in result.issues:
            detail = issue.message.replace("|", "\\|")
            lines.append(f"| `{issue.code}` | `{issue.path}:{issue.line}` | {detail} |")
    else:
        lines.append("No active Markdown documentation issues found.")
    lines.append("")
    lines.append("## Active files scanned")
    lines.append("")
    for path in result.active_docs:
        lines.append(f"- `{rel(path, result.root)}`")
    lines.append("")
    lines.append("## Verification")
    lines.append("")
    lines.append("- Clean active docs: `python3 tools/generate_active_docs_report.py --check`")
    lines.append("- Seeded invalid fixture: `python3 tools/generate_active_docs_report.py --fixture invalid`")
    lines.append("- Seeded clean fixture: `python3 tools/generate_active_docs_report.py --fixture clean`")
    lines.append("")
    return "\n".join(lines)


def analyze(root: Path) -> ReportResult:
    active_docs, excluded_docs = collect_active_docs(root)
    active_set = set(active_docs)
    issues: list[Issue] = []
    link_issues, links = check_links(active_docs, active_set, root)
    issues.extend(link_issues)
    issues.extend(check_duplicate_character_names(active_docs, root))
    issues.extend(check_contradictory_dates(active_docs, root))
    issues.extend(check_missing_references(active_docs, root))
    issues.sort(key=lambda issue: (issue.code, issue.path, issue.line, issue.message))
    placeholder = ReportResult(root, active_docs, excluded_docs, links, issues, "")
    rendered = render_report(placeholder)
    return ReportResult(root, active_docs, excluded_docs, links, issues, rendered)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate active Markdown documentation report for P0-031")
    parser.add_argument("--check", action="store_true", help="fail when active docs contain issues or the report is stale")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="report output path; defaults to docs/reports/active_markdown_report.md")
    parser.add_argument("--fixture", choices=("clean", "invalid"), help="run against a seeded in-memory fixture instead of the repository")
    args = parser.parse_args()

    if args.fixture:
        return run_fixture(args.fixture, analyze)

    result = analyze(ROOT)
    output = Path(args.output)
    if not output.is_absolute():
        output = ROOT / output

    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        stale = current != result.rendered
        if stale:
            print(f"{rel(output, ROOT)} is not up to date", file=sys.stderr)
        if result.issues:
            print(f"active Markdown docs contain {len(result.issues)} issue(s)", file=sys.stderr)
        if stale or result.issues:
            return 1
        print(f"{rel(output, ROOT)} is up to date and active Markdown docs have zero issues")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(result.rendered, encoding="utf-8")
    print(f"wrote {rel(output, ROOT)} with {len(result.issues)} issue(s)")
    return 1 if result.issues else 0


if __name__ == "__main__":
    raise SystemExit(main())
