#!/usr/bin/env python3
"""Agent CLI for the physical-object catalog (content/objects/).

    list   [--category C] [--handling H] [--lifecycle L] [--tag T] [--text S] [--ids]
    show   OBJ_ID
    set    OBJ_ID path=json [path=json ...]     e.g. physical.mass_kg=4.5 'tags=["tool","iron"]'
    sync                                        # re-measure GLBs, refresh sizes/lifecycle
    prompts [--missing-icons] [--out FILE]      # image-generation prompts (JSONL)
    index                                       # rewrite the table in docs/SYSTEMS/OBJECT_CATALOG.md
    index --check                               # fail if that table is stale

After any edit run `python3 tools/validate_object_catalog.py`.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

import object_catalog_lib as lib  # noqa: E402

DOC = lib.ROOT / "docs" / "SYSTEMS" / "OBJECT_CATALOG.md"
INDEX_START = "<!-- object-catalog-index:start (generated by tools/object_catalog.py index; do not edit) -->"
INDEX_END = "<!-- object-catalog-index:end -->"


def _entries() -> list[dict[str, Any]]:
    return lib.load_catalog()


def _find(object_id: str) -> dict[str, Any]:
    for entry in _entries():
        if entry["id"] == object_id:
            return entry
    raise SystemExit(f"unknown object id {object_id!r}")


def _summary(entry: dict[str, Any]) -> str:
    mass = entry["physical"]["mass_kg"]
    return (
        f"{entry['id']:<40} {entry['category']:<14} {entry['handling']:<16} "
        f"{mass:>7g} kg  {entry['lifecycle']}"
    )


def cmd_list(args: argparse.Namespace) -> int:
    count = 0
    for entry in _entries():
        if args.category and entry["category"] != args.category:
            continue
        if args.handling and entry["handling"] != args.handling:
            continue
        if args.lifecycle and entry["lifecycle"] != args.lifecycle:
            continue
        if args.tag and args.tag not in entry["tags"]:
            continue
        if args.text:
            hay = (entry["name"] + " " + entry["description"] + " " + " ".join(entry["tags"])).lower()
            if args.text.lower() not in hay:
                continue
        print(entry["id"] if args.ids else _summary(entry))
        count += 1
    if not args.ids:
        print(f"{count} object(s)")
    return 0


def cmd_show(args: argparse.Namespace) -> int:
    print(json.dumps(_find(args.id), indent=2, ensure_ascii=False))
    return 0


def _set_path(data: dict[str, Any], dotted: str, value: Any) -> None:
    parts = dotted.split(".")
    cursor = data
    for part in parts[:-1]:
        cursor = cursor.setdefault(part, {})
    if value is None:
        cursor.pop(parts[-1], None)
    else:
        cursor[parts[-1]] = value


def cmd_set(args: argparse.Namespace) -> int:
    entry = _find(args.id)
    for assignment in args.assignments:
        if "=" not in assignment:
            raise SystemExit(f"expected path=json, got {assignment!r}")
        dotted, raw = assignment.split("=", 1)
        try:
            value = json.loads(raw)
        except json.JSONDecodeError:
            value = raw  # bare strings are fine
        _set_path(entry, dotted, value)
    _refresh(entry)
    lib.dump_json(lib.entry_path(entry), entry)
    print(f"updated {lib.entry_path(entry).relative_to(lib.ROOT)}")
    return 0


def _refresh(entry: dict[str, Any]) -> bool:
    """Re-derive measured size, physical.size_m and lifecycle. Returns True if changed."""
    before = json.dumps(entry, sort_keys=True)
    model = entry["model"]
    if model["status"] == "glb":
        from object_catalog_glb import GlbFile

        glb = GlbFile.load(lib.res_to_path(model["glb"]))
        node = model.get("node") or next(iter(model.get("states", {}).values()), None)
        index = glb.find_node(node) if node else None
        bounds = glb.triangles(index).bounds()
        if bounds is not None:
            measured = [round(float(v), 2) for v in bounds[1] - bounds[0]]
            model["measured_size_m"] = measured
            entry["physical"]["size_m"] = measured
    entry["lifecycle"] = lib.expected_lifecycle(entry)
    return json.dumps(entry, sort_keys=True) != before


def cmd_sync(_: argparse.Namespace) -> int:
    changed = 0
    for entry in _entries():
        if _refresh(entry):
            lib.dump_json(lib.entry_path(entry), entry)
            changed += 1
            print(f"synced {entry['id']}")
    print(f"{changed} object(s) updated")
    return 0


def prompt_for(entry: dict[str, Any]) -> str:
    size = " x ".join(f"{v:g}" for v in entry["physical"]["size_m"])
    mats = ", ".join(m.replace("_", " ") for m in entry["physical"]["materials"])
    return (
        f"{entry['visual']['image_prompt'].rstrip('. ')}. "
        f"Real size about {size} m; materials: {mats}. {lib.style_suffix()}."
    )


def cmd_prompts(args: argparse.Namespace) -> int:
    lines = []
    for entry in _entries():
        if args.missing_icons and entry["visual"]["icon_status"] != "missing":
            continue
        lines.append(
            json.dumps(
                {
                    "id": entry["id"],
                    "output": entry["visual"]["icon"],
                    "prompt": prompt_for(entry),
                    "reference_preview": entry["visual"]["preview"] if entry["model"]["status"] == "glb" else None,
                },
                ensure_ascii=False,
            )
        )
    text = "\n".join(lines) + ("\n" if lines else "")
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"wrote {len(lines)} prompt(s) to {args.out}")
    else:
        sys.stdout.write(text)
    return 0


def build_index(entries: list[dict[str, Any]]) -> str:
    rows = [
        "| ID | Name | Category | Handling | Mass (kg) | Actions | Edible | Model | Lifecycle |",
        "|----|------|----------|----------|----------:|---------|:------:|-------|-----------|",
    ]
    for entry in sorted(entries, key=lambda e: (e["category"], e["id"])):
        model = entry["model"]
        kind = model["status"]
        if kind == "glb":
            glb = model["glb"].replace("res://assets/", "")
            node = model.get("node") or ("states" if "states" in model else "")
            kind = f"`{glb}`" + (f" › {node}" if node else "")
        elif kind == "procedural":
            kind = f"procedural (`{model['prop_kind']}`)"
        actions = ", ".join(a for a in entry["actions"] if a not in {"inspect", "drop"})
        edible = "yes" if "edible" in entry else ""
        rows.append(
            f"| `{entry['id']}` | {entry['name']} | {entry['category']} | {entry['handling']} | "
            f"{entry['physical']['mass_kg']:g} | {actions} | {edible} | {kind} | {entry['lifecycle']} |"
        )
    counts: dict[str, int] = {}
    for entry in entries:
        counts[entry["lifecycle"]] = counts.get(entry["lifecycle"], 0) + 1
    summary = ", ".join(f"{n} {name}" for name, n in sorted(counts.items()))
    return f"{len(entries)} objects ({summary}).\n\n" + "\n".join(rows)


def cmd_index(args: argparse.Namespace) -> int:
    text = DOC.read_text(encoding="utf-8")
    start = text.index(INDEX_START) + len(INDEX_START)
    end = text.index(INDEX_END)
    fresh = text[:start] + "\n\n" + build_index(_entries()) + "\n\n" + text[end:]
    if args.check:
        if fresh != text:
            print(f"{DOC.relative_to(lib.ROOT)} index is stale: run `python3 tools/object_catalog.py index`")
            return 1
        return 0
    DOC.write_text(fresh, encoding="utf-8")
    print(f"updated {DOC.relative_to(lib.ROOT)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p_list = sub.add_parser("list")
    p_list.add_argument("--category")
    p_list.add_argument("--handling")
    p_list.add_argument("--lifecycle")
    p_list.add_argument("--tag")
    p_list.add_argument("--text")
    p_list.add_argument("--ids", action="store_true")
    p_list.set_defaults(func=cmd_list)

    p_show = sub.add_parser("show")
    p_show.add_argument("id")
    p_show.set_defaults(func=cmd_show)

    p_set = sub.add_parser("set")
    p_set.add_argument("id")
    p_set.add_argument("assignments", nargs="+")
    p_set.set_defaults(func=cmd_set)

    sub.add_parser("sync").set_defaults(func=cmd_sync)

    p_prompts = sub.add_parser("prompts")
    p_prompts.add_argument("--missing-icons", action="store_true")
    p_prompts.add_argument("--out")
    p_prompts.set_defaults(func=cmd_prompts)

    p_index = sub.add_parser("index")
    p_index.add_argument("--check", action="store_true")
    p_index.set_defaults(func=cmd_index)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
