#!/usr/bin/env python3
"""Keep the generated census roster block in docs/CITIZENS/factions/<id>.md accurate.

Each faction page is written by hand (motives, cells, places, tensions) and carries a block

    <!-- census-roster:start -->
    ...
    <!-- census-roster:end -->

that this tool rewrites from docs/data/city_census.json: head-count, spread by district, role, ethnicity,
sex, age, trade, and a table of members who have deep cards.

  python3 tools/city/build_faction_rosters.py            # rewrite blocks
  python3 tools/city/build_faction_rosters.py --check    # fail if a block is stale
  python3 tools/city/build_faction_rosters.py --packets DIR   # writer packets (JSON) for faction pages
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_city_census as bc  # noqa: E402

ROOT = bc.ROOT
CIT = ROOT / "docs/CITIZENS"
PLAN = ROOT / "docs/data/citizen_cards_plan.json"
START, END = "<!-- census-roster:start (generated by tools/city/build_faction_rosters.py; do not edit) -->", "<!-- census-roster:end -->"
AGE_BANDS = [("0-14", 0, 14), ("15-29", 15, 29), ("30-44", 30, 44), ("45-59", 45, 59), ("60+", 60, 200)]


def label(t):
    return bc.TRADES.get(t, t.replace("_", " "))


def collect():
    census = json.loads(bc.OUT_JSON.read_text(encoding="utf-8"))
    plan = json.loads(PLAN.read_text(encoding="utf-8"))
    H = {h["id"]: h for h in census["households"]}
    carded = set(plan["cards"])
    by = {f: [] for f in bc.FACTIONS}
    for p in census["persons"]:
        by[p["faction"]].append(p)
    return census, H, carded, by


def block(fid, members, H, carded, total):
    n = len(members)
    out = [START, "", f"### Census roster ({n} residents, {100 * n / total:.1f}% of {total})", "",
           "Counts inside the walls and the immediate suburbs only; the hinterland is outside the census (see this page's text for estimates).", ""]

    def tbl(title, counter, order=None, labelmap=None):
        out.extend([f"**{title}**", "", "| Group | Residents |", "|---|---:|"])
        for k in (order or [k for k, _ in counter.most_common()]):
            if counter.get(k):
                out.append(f"| {(labelmap or {}).get(k, k)} | {counter[k]} |")
        out.append("")

    tbl("By district", Counter(H[p["household"]]["district"] for p in members), list(bc.DISTRICT_NAME), bc.DISTRICT_NAME)
    tbl("By role in the faction", Counter(p["faction_role"].replace("_", " ") for p in members))
    tbl("By ethnicity", Counter(p["ethnicity"] for p in members))
    tbl("By sex", Counter("female" if p["sex"] == "f" else "male" for p in members))
    ab = Counter()
    for p in members:
        for name, lo, hi in AGE_BANDS:
            if lo <= p["age"] <= hi:
                ab[name] += 1
    tbl("By age", ab, [a for a, _, _ in AGE_BANDS])
    tc = Counter(label(p["trade"]) for p in members if p["age"] >= 14)
    out.extend(["**Most common trades (age 14+):** " + (", ".join(f"{k} {v}" for k, v in tc.most_common(14)) or "none"), ""])
    out.extend(["**Streets with the most members:** " + ", ".join(f"{k} {v}" for k, v in Counter(H[p["household"]]["street"] for p in members).most_common(10)), ""])
    cm = sorted((p for p in members if p["id"] in carded), key=lambda p: (-p["age"] if p.get("office") else 0, p["name"]))
    out.extend([f"**Members with deep cards ({len(cm)}):**", "", "| Name | Age | Trade | Street | Role |", "|---|---:|---|---|---|"])
    for p in cm:
        dcode = H[p["household"]]["district"]
        off = f" ({p['office'].replace('_', ' ')})" if p.get("office") else ""
        out.append(f"| [{p['name']}](../{bc.card_rel(p, dcode)}) | {p['age']}{p['sex']} | {label(p['trade'])}{off} | {H[p['household']]['street']} | {p['faction_role'].replace('_', ' ')} |")
    out.extend(["", END])
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--packets")
    args = ap.parse_args(argv)
    census, H, carded, by = collect()
    total = len(census["persons"])
    if args.packets:
        outd = Path(args.packets)
        outd.mkdir(parents=True, exist_ok=True)
        for fid, members in by.items():
            pk = {"faction": fid, "label": bc.FACTION_LABELS[fid], "residents": len(members), "total_census": total, "roster_block": block(fid, members, H, carded, total),
                  "carded_members": [{"name": p["name"], "link": f"../{bc.card_rel(p, H[p['household']]['district'])}", "age": p["age"], "sex": p["sex"],
                                      "trade": label(p["trade"]), "street": H[p["household"]]["street"], "role": p["faction_role"], "ethnicity": p["ethnicity"],
                                      "office": p.get("office"), "household": p["household"]}
                                     for p in sorted(members, key=lambda p: p["name"]) if p["id"] in carded]}
            (outd / f"{fid}.json").write_text(json.dumps(pk, ensure_ascii=False, indent=1), encoding="utf-8")
        print("packets ->", outd)
        return 0
    stale = []
    for fid, members in by.items():
        if fid == "none":
            continue
        page = CIT / "factions" / f"{fid}.md"
        if not page.exists():
            continue
        text = page.read_text(encoding="utf-8")
        new = block(fid, members, H, carded, total)
        if START in text and END in text:
            head, rest = text.split(START, 1)
            _, tail = rest.split(END, 1)
            newtext = head + new + tail
        else:
            newtext = text.rstrip() + "\n\n" + new + "\n"
        if args.check:
            if newtext != text:
                stale.append(fid)
        else:
            page.write_text(newtext, encoding="utf-8")
    if args.check and stale:
        print("faction roster blocks are stale:", stale, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
