#!/usr/bin/env python3
"""Generate docs/CITIZENS/ledger/<district>/<street>.md and docs/CITIZENS/census_tables.md from the census.

  python3 tools/city/build_citizen_ledger.py           # rewrite pages
  python3 tools/city/build_citizen_ledger.py --check   # fail if pages are stale

Every resident of the census appears in exactly one ledger row. Residents that have a card link to it.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_city_census as bc  # noqa: E402

ROOT = bc.ROOT
CIT = ROOT / "docs/CITIZENS"
PLAN = ROOT / "docs/data/citizen_cards_plan.json"

CLASS_NOTE = {
    "shed": "outbuilding or warehouse (caretaker at most)", "poor": "small dwelling", "master": "craft house with workshop",
    "merchant": "merchant house with rear court", "great": "great house", "institution": "institution",
}
FACTION_SHORT = bc.FACTION_LABELS


def label(t):
    return bc.TRADES.get(t, t.replace("_", " "))


def person_row(p, has_card, dcode):
    a = p["appearance"]
    name = f"[{p['name']}](../../{bc.card_rel(p, dcode)})" if has_card else p["name"]
    off = f" ({p['office'].replace('_', ' ')})" if p.get("office") else ""
    look = f"{a['height_cm']} cm, {a['build']}, {a['hair']}, {a['eyes']} eyes"
    fac = FACTION_SHORT[p["faction"]] + (f" - {p['faction_role'].replace('_', ' ')}" if p["faction"] != "none" else "")
    return (f"| `{p['id']}` | {name} | {p['age']}{p['sex']} | {p['household_role']} | {label(p['trade'])}{off} | {p['ethnicity']} | {fac} | {look} |")


def build_pages():
    census = json.loads(bc.OUT_JSON.read_text(encoding="utf-8"))
    plan = json.loads(PLAN.read_text(encoding="utf-8"))
    carded = set(plan["cards"])
    P = {p["id"]: p for p in census["persons"]}
    pages = {}
    by_page = defaultdict(list)
    for h in census["households"]:
        if not h["members"]:
            continue
        by_page[(h["district"], h["street"])].append(h)
    index_rows = []
    for (dcode, street), hhs in sorted(by_page.items(), key=lambda kv: (kv[0][0], kv[0][1])):
        hhs.sort(key=lambda h: (h["xy"][0], h["xy"][1], h["id"]))
        n = sum(len(h["members"]) for h in hhs)
        nc = sum(1 for h in hhs for m in h["members"] if m in carded)
        rel = f"ledger/{bc.DISTRICT_DIR[dcode]}/{bc.street_slug(street)}.md"
        lines = [f"# Ledger: {street} ({bc.DISTRICT_NAME[dcode]})", "",
                 "Generated by `tools/city/build_citizen_ledger.py` from [`city_census.json`](../../../data/city_census.json); do not edit by hand. "
                 "Method and bracket: [`CENSUS.md`](../../CENSUS.md). Rows with a link have a deep card; the others are census seeds ready for promotion "
                 "(see [`WRITING_CARDS.md`](../../WRITING_CARDS.md)).", "",
                 f"{len(hhs)} households, {n} residents, {nc} with cards.", ""]
        for h in hhs:
            ms = [P[m] for m in h["members"]]
            ages = Counter("child" if q["age"] < 15 else "adult" if q["age"] < 60 else "elder" for q in ms)
            title = h.get("name") or f"plot {h['building'].replace('bldg.', '')}"
            lines += [f'<a id="{bc.hh_anchor(h["id"])}"></a>', "",
                      f"## {title} ({h['id']})", "",
                      f"- **Street:** {street}; **zone:** {h['zone']}; **class:** {h['class']} - {CLASS_NOTE.get(h['class'], '')}; **footprint:** {h['area_m2']} m2; "
                      f"**building:** `{h['building'] or 'n/a (institution)'}`; **map position:** ({h['xy'][0]}, {h['xy'][1]}) m from the forum.",
                      f"- **Residents:** {len(ms)} ({ages['child']} under 15, {ages['adult']} adults, {ages['elder']} aged 60+).", "",
                      "| ID | Name | Age | Role | Trade | Ethnicity | Faction | Look seed |", "|---|---|---|---|---|---|---|---|"]
            for q in ms:
                lines.append(person_row(q, q["id"] in carded, dcode))
            lines.append("")
        pages[rel] = "\n".join(lines).rstrip() + "\n"
        index_rows.append((dcode, street, rel, len(hhs), n, nc))
    # ledger index
    idx = ["# Ledger", "",
           "Every household and resident of the 1343 census, one page per street. Generated by `tools/city/build_citizen_ledger.py`; method in [`CENSUS.md`](../CENSUS.md).", ""]
    cur = None
    for dcode, street, rel, nh, n, nc in index_rows:
        if dcode != cur:
            cur = dcode
            idx += ["", f"## {bc.DISTRICT_NAME[dcode]}", "", "| Street | Households | Residents | Cards |", "|---|---:|---:|---:|"]
        idx.append(f"| [{street}]({rel[len('ledger/'):]}) | {nh} | {n} | {nc} |")
    idx += ["", "## All files in this folder", "", "<!-- docs-index:start (generated by tools/docs_index.py; do not edit) -->", "",
            "_Every file in this folder is linked above._", "", "<!-- docs-index:end -->"]
    pages["ledger/README.md"] = "\n".join(idx) + "\n"
    pages["census_tables.md"] = tables_page(census, plan, P)
    return pages


def pct(n, tot):
    return f"{100 * n / tot:.1f}%"


def tables_page(census, plan, P):
    st = bc.pop_stats(census)
    tot = st["total"]
    carded = len(plan["cards"])
    out = ["# Census tables", "",
           "Generated by `tools/city/build_citizen_ledger.py`; do not edit by hand. Bracket and caveats: [`CENSUS.md`](./CENSUS.md).", "",
           f"**{tot}** residents in **{sum(1 for h in census['households'] if h['members'])}** households; **{carded}** have deep cards ({pct(carded, tot)}).", ""]

    def table(title, counter, order=None, labelmap=None):
        out.extend([f"## {title}", "", "| Group | Residents | Share |", "|---|---:|---:|"])
        keys = order or [k for k, _ in counter.most_common()]
        for k in keys:
            if k in counter:
                out.append(f"| {(labelmap or {}).get(k, k)} | {counter[k]} | {pct(counter[k], tot)} |")
        out.append("")

    table("By district", st["by_district"], list(bc.DISTRICT_NAME), bc.DISTRICT_NAME)
    table("By sex", st["sex"], ["f", "m"], {"f": "female", "m": "male"})
    table("By age band", st["age"], ["0-4", "5-14", "15-29", "30-44", "45-59", "60-+"])
    table("By ethnicity", st["eth"])
    table("By segment", st["segment"])
    table("By faction affinity", st["faction"], None, bc.FACTION_LABELS)
    # by trade, grouped
    groups = {
        "Children, scholars and infants": ["infant", "child", "scholar"],
        "Household service": ["servant", "maid", "cook", "stable_hand", "castle_servant", "castle_cook", "apprentice", "journeyman", "clerk"],
        "Food and drink": ["baker", "brewer", "alewife", "innkeeper", "butcher", "fishmonger", "miller", "greengrocer", "saltmonger", "dairy"],
        "Metal, wood, stone": ["smith", "goldsmith", "armourer", "nailsmith", "cutler", "cooper", "carpenter", "mason", "tiler", "wheelwright", "joiner",
                               "limeburner", "brickmaker", "glazier"],
        "Cloth, leather, dress": ["weaver", "dyer", "tailor", "furrier", "shoemaker", "tanner", "saddler", "glover", "hatter", "spinner", "belt_maker", "comb_maker"],
        "Sea, harbour, haulage": ["fisher", "net_maker", "boatman", "shipwright", "ropemaker", "sailmaker", "carter", "porter", "drover", "sailor", "skipper",
                                  "pilot", "ballast_man", "labourer"],
        "Trade, finance, civic": ["merchant", "retailer", "moneylender", "weigher", "scribe", "stadtschreiber", "ratsdiener", "watch_sergeant", "gatekeeper",
                                  "town_herdsman", "executioner", "gravedigger", "councillor"],
        "Care, craft services, other": ["barber", "midwife", "bathkeeper", "apothecary", "healer", "washerwoman", "chandler", "tallow", "potter", "gardener",
                                        "farmer", "woodcutter", "musician", "pedlar", "retired", "widow", "pilgrim", "hospital_inmate"],
        "Church": ["priest", "chaplain", "monk", "nun", "canon", "vicar", "sexton", "lay_brother", "lay_sister"],
        "Crown, castle and foreign": ["knight", "squire", "man_at_arms", "crown_clerk", "chamberlain", "falconer", "novgorod_merchant", "novgorod_clerk"],
    }
    out += ["## By occupation group", "", "| Group | Residents | Share | Trades |", "|---|---:|---:|---|"]
    assigned = set()
    for g, keys in groups.items():
        c = sum(st["trade"].get(k, 0) for k in keys)
        assigned.update(keys)
        top = ", ".join(f"{bc.TRADES.get(k, k)} {st['trade'][k]}" for k in sorted(keys, key=lambda k: -st["trade"].get(k, 0)) if st["trade"].get(k))
        out.append(f"| {g} | {c} | {pct(c, tot)} | {top} |")
    rest = {k: v for k, v in st["trade"].items() if k not in assigned}
    if rest:
        out.append(f"| Other | {sum(rest.values())} | {pct(sum(rest.values()), tot)} | {', '.join(f'{k} {v}' for k, v in rest.items())} |")
    out.append("")
    # faction by district matrix
    mat = defaultdict(Counter)
    H = {h["id"]: h for h in census["households"]}
    for p in census["persons"]:
        mat[p["faction"]][H[p["household"]]["district"]] += 1
    cols = [c for c in bc.DISTRICT_NAME if any(mat[f][c] for f in mat)]
    out += ["## Faction by district", "", "| Faction | " + " | ".join(bc.DISTRICT_NAME[c] for c in cols) + " | Total |", "|---|" + "---:|" * (len(cols) + 1)]
    for f in bc.FACTIONS:
        if f in mat:
            out.append(f"| {bc.FACTION_LABELS[f]} | " + " | ".join(str(mat[f][c]) for c in cols) + f" | {sum(mat[f].values())} |")
    out.append("")
    # buildings by district
    dist_rows = defaultdict(lambda: [0, 0, 0, 0.0])
    for h in census["households"]:
        if h["kind"] == "institution":
            continue
        r = dist_rows[h["district"]]
        r[0] += 1
        r[1] += 1 if h["members"] else 0
        r[2] += len(h["members"])
        r[3] += h["area_m2"]
    out += ["## Plot buildings by district", "", "Churches, the chapel, the town hall and the castle are institutions and are not counted here.", "",
            "| District | Houses in the plan | Inhabited | Residents | Residents per inhabited house | Mean footprint (m2) |", "|---|---:|---:|---:|---:|---:|"]
    for code in bc.DISTRICT_NAME:
        if code in dist_rows:
            r = dist_rows[code]
            out.append(f"| {bc.DISTRICT_NAME[code]} | {r[0]} | {r[1]} | {r[2]} | {r[2] / max(r[1], 1):.1f} | {r[3] / r[0]:.0f} |")
    out.append("")
    # buildings
    out += ["## Buildings by size class", "", "| Class | Plots | Residents | Mean per plot |", "|---|---:|---:|---:|"]
    cc = Counter()
    rr = Counter()
    for h in census["households"]:
        cc[h["class"]] += 1
        rr[h["class"]] += len(h["members"])
    for k in ["shed", "poor", "master", "merchant", "great", "institution"]:
        if cc[k]:
            out.append(f"| {k} - {CLASS_NOTE[k]} | {cc[k]} | {rr[k]} | {rr[k] / cc[k]:.1f} |")
    out.append("")
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    pages = build_pages()
    stale = []
    for rel, text in pages.items():
        path = CIT / rel
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    ledger_root = CIT / "ledger"
    if args.check:
        extra = [p.relative_to(CIT).as_posix() for p in ledger_root.rglob("*.md") if p.relative_to(CIT).as_posix() not in pages]
        if stale or extra:
            print("citizen ledger is stale: run python3 tools/city/build_citizen_ledger.py", stale[:5], extra[:5], file=sys.stderr)
            return 1
        return 0
    print(f"wrote {len(pages)} pages under {CIT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
