#!/usr/bin/env python3
"""Roster of who stands where, generated from the runtime citizens file.

  python3 tools/city/build_gate_garrison_doc.py            # write docs/CITIZENS/gate_garrisons.md
  python3 tools/city/build_gate_garrison_doc.py --check    # fail when the committed page is stale

Reads content/world/reval_city/citizens.json (see tools/city/gate_garrisons.py and
docs/SYSTEMS/GATE_GARRISONS.md); every row is a census resident with a stable id.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools/city"))
import gate_garrisons  # noqa: E402

CITIZENS = ROOT / "content/world/reval_city/citizens.json"
OUT = ROOT / "docs/CITIZENS/gate_garrisons.md"
KIT = {"watch": "kettle hat, spear", "crown": "kettle hat, spear, red tunic",
       "sergeant": "kettle hat, sword", "keeper": "own clothes, keys"}
ORDER = {"gatekeeper": 0, "sergeant": 1, "watchman": 2, "man_at_arms": 3}


def build() -> str:
    data = json.loads(CITIZENS.read_text())
    places = data["places"]
    on_duty = [r for r in data["residents"] if "duty" in r]
    lines = [
        "# Gate garrisons and patrols (generated)",
        "",
        "Generated by `tools/city/build_gate_garrison_doc.py` from `content/world/reval_city/citizens.json`; "
        "do not edit. Design and rules: [`docs/SYSTEMS/GATE_GARRISONS.md`](../SYSTEMS/GATE_GARRISONS.md). "
        "Every row is a census resident ([`CENSUS.md`](./CENSUS.md)); *walk* is the distance from their house door to the post.",
        "",
        f"{len(on_duty)} residents are on duty posts.",
    ]
    posts = list(gate_garrisons.GATES) + ["patrol.pikk", "patrol.lai", "patrol.vene", "patrol.toompea_wall"]
    for post in posts:
        rows = [r for r in on_duty if r["duty"]["post"] == post]
        if not rows:
            continue
        label = rows[0]["duty"]["label"]
        why = gate_garrisons.GATES.get(post, {}).get("reason", "")
        lines += ["", f"## {label} (`{post}`)", ""]
        if why:
            lines += [f"Why: {why}.", ""]
        lines += ["| Shift | Role | Resident | Faction | Lives | Walk | Kit |", "|---|---|---|---|---|---|---|"]
        for r in sorted(rows, key=lambda r: (r["duty"]["shift"] != "day", ORDER[r["duty"]["role"]], r["id"])):
            h, w = places[r["home"]], places[r["work"]]
            walk = round(math.hypot(h[0] - w[0], h[1] - w[1]) / 10) * 10
            lines.append(f"| {r['duty']['shift']} | {r['duty']['role'].replace('_', ' ')} | "
                         f"{r['name']} (`{r['id']}`, {r['trade'].replace('_', ' ')}) | {r['faction']} | "
                         f"{r['street']} | {walk} m | {KIT[r['duty']['kit']]} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    text = build()
    if parser.parse_args().check:
        if not OUT.is_file() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run tools/city/build_gate_garrison_doc.py")
            return 1
        print("gate_garrisons.md up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
